name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-python:
    name: Test across python versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8', '3.9' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          pip install -r requirements.txt
          pip install .
      - run: python -m unittest
  test-engine:
    name: Test across container engines
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        container-engine: [ 'docker', 'podman' ]
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          pip install -r requirements.txt
          pip install .
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Test
        env:
          ENGINE_TO_TEST: ${{ matrix.container-engine }}
        run: test/with_engine_mask.sh python -m unittest
